[package]

name = "bitio"
version = "0.0.3"
authors = ["Florian Wilkens <mrfloya_github@outlook.com>"]
license = "MIT"
repository = "https://github.com/MrFloya/bitio.rs"

description = "Basic bitwise IO for Rust."

[dependencies]
log = "*"
